name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter (automatically fetches and installs the correct Flutter SDK)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # You can specify a version like '3.10.5'

      # Step 3: Run Flutter pub get to install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze the project to check for potential issues (lint)
      - name: Run Flutter analyze
        run: flutter analyze

      # Step 5: Run unit and widget tests
      - name: Run tests
        run: flutter test

      # Optional Step: Build the app (e.g., for Android)
      - name: Build APK
        run: flutter build apk --release

      # Optional Step: Cache Flutter SDK and dependencies to speed up future builds
      - name: Cache Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter

      # Step 6: If tests fail, GitHub will automatically show this in the Pull Request or push request
