name: Push Build to Widgetbook Cloud

on:
  push:
    branches:
      - main

jobs:
  push-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build -d

      - name: Build Widgetbook
        run: flutter build web -t lib/widgetbook/widgetbook.dart

      # - name: Install Widgetbook CLI
      #   run: dart pub global activate --source path ../packages/widgetbook_cli

      # - name: Push Build
      #   run: widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }}
